name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build
      - name: Get current version
        id: get_version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT
      - name: Create release
        run: gh release create v${{ steps.get_version.outputs.version }} -t v${{ steps.get_version.outputs.version }}
      - name: Upload artifact
        run: |
          mv ./maimodorun.zip maimodorun-v${{ steps.get_version.outputs.version }}.zip
          gh release upload v${{ steps.get_version.outputs.version }} maimodorun-v${{ steps.get_version.outputs.version }}.zip
